name: bench
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - awscli
  - bcftools
  - mamba
  - samtools
  - severus=1.3
  - pip:
    - dysgu==1.8.7
    - cuteSV==2.0.2
    - sniffles==2.6.3
    - Truvari==5.3
    - plotly==5.24.1
    - matplotlib
    - seaborn
    - pandas
    - tabulate
